language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://dbarber.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "Zy+7WdEmVSt12nO9vdcMmi6KmXFL9wD90dgQasbK4tSo+7N1OmG9usleb7TZEtwnFqLc2657q0pLWfaLRnh3evGBRZRJhfNHb2qGKZk55tRE3sHVH/qgfnDDmpybaXkdBQpSyC6kLgyQ6+KAL6ps1f1pyjqFmERjIlYoL3nsQ1bYu7tT7pGGIhOVqplpheYmvvyxh7w5FXBEwkgj72lG+uSc+mgDDqNUqfx7rY3EYYHw5AZFRIvSWAa9O31Ii4Nr/y8+GIlkuinfLfM7lDBCuuQ4V5dAhlisms9l5Km1LJRygHRHg8IuRBumtelBXmdetsAEUMcDgSP6OSUe2CIGjIo4TdtCMbRPDpTz8JPuJtGhyryhY3u+DuOzegc30Ybpk33gKED2U5uwyvV+2kxg8vYUb7wJuMVT5HxYrmVjuxwZC+M4kHO/6pDsFxJMFqe0kwvjMCT8Vf/U5gpzA/TlZcYWWB8emNCXAxfDKqxw2x2JukMHGQDjvlAorzfi3cQLvUd/r+0w8yc/rHMG8lFrh9z/v3iXwFeOBw0vsiSBTGHn9CAXitBxH12u7j4KchQpvt7drL9qlVgXOiSGCtAnA/RknerDTu9UTIzfx0XgOCZnke/Kkw9Jehtrv79AI2ku5GoC6NTUh17iANVSBcEghJm1Ho8VdL+jtEaVy4dNsh0="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
